import type { ProfileStats } from './stats';

export interface Award {
  id: string;
  name: string;
  description: string;
  icon: string;
  shape: 'shield' | 'star' | 'hexagon' | 'circle';
  color: string; // gradient start
  color2: string; // gradient end
  category: 'milestone' | 'movies' | 'tv' | 'anime' | 'reviews' | 'watchtime';
  isUnlocked: (stats: ProfileStats) => boolean;
  unlockHint: string; // shown when locked
}

export const AWARDS: Award[] = [
  // ── Milestone ────────────────────────────────────────────────────────
  {
    id: 'first_step',
    name: 'First Step',
    description: 'Added your first title to the list.',
    icon: '🎯',
    shape: 'circle',
    color: '#6366f1',
    color2: '#8b5cf6',
    category: 'milestone',
    isUnlocked: (s) => s.watched.totalCount >= 1 || s.planned.totalCount >= 1,
    unlockHint: 'Add your first title',
  },
  {
    id: 'enthusiast',
    name: 'Enthusiast',
    description: 'Reached a profile score of 5.',
    icon: '🎬',
    shape: 'circle',
    color: '#3b82f6',
    color2: '#06b6d4',
    category: 'milestone',
    isUnlocked: (s) => s.score >= 5,
    unlockHint: 'Reach profile score 5',
  },
  {
    id: 'cinephile',
    name: 'Cinephile',
    description: 'Reached a profile score of 20.',
    icon: '🎭',
    shape: 'hexagon',
    color: '#8b5cf6',
    color2: '#ec4899',
    category: 'milestone',
    isUnlocked: (s) => s.score >= 20,
    unlockHint: 'Reach profile score 20',
  },
  {
    id: 'film_scholar',
    name: 'Film Scholar',
    description: 'Reached a profile score of 50.',
    icon: '🏆',
    shape: 'shield',
    color: '#f59e0b',
    color2: '#f97316',
    category: 'milestone',
    isUnlocked: (s) => s.score >= 50,
    unlockHint: 'Reach profile score 50',
  },
  {
    id: 'auteur',
    name: 'Auteur',
    description: 'Reached a profile score of 100.',
    icon: '🌟',
    shape: 'star',
    color: '#ec4899',
    color2: '#f43f5e',
    category: 'milestone',
    isUnlocked: (s) => s.score >= 100,
    unlockHint: 'Reach profile score 100',
  },
  {
    id: 'legendary',
    name: 'Legendary',
    description: 'Reached a profile score of 200.',
    icon: '👑',
    shape: 'star',
    color: '#06b6d4',
    color2: '#6366f1',
    category: 'milestone',
    isUnlocked: (s) => s.score >= 200,
    unlockHint: 'Reach profile score 200',
  },

  // ── Movies ────────────────────────────────────────────────────────────
  {
    id: 'silver_screen',
    name: 'Silver Screen',
    description: 'Watched your first movie.',
    icon: '🎞️',
    shape: 'circle',
    color: '#6b7280',
    color2: '#9ca3af',
    category: 'movies',
    isUnlocked: (s) => s.watched.MOVIE.count >= 1,
    unlockHint: 'Watch your first movie',
  },
  {
    id: 'movie_buff',
    name: 'Movie Buff',
    description: 'Watched 10 movies.',
    icon: '🍿',
    shape: 'circle',
    color: '#f97316',
    color2: '#eab308',
    category: 'movies',
    isUnlocked: (s) => s.watched.MOVIE.count >= 10,
    unlockHint: 'Watch 10 movies',
  },
  {
    id: 'film_fanatic',
    name: 'Film Fanatic',
    description: 'Watched 50 movies.',
    icon: '📽️',
    shape: 'hexagon',
    color: '#ef4444',
    color2: '#f97316',
    category: 'movies',
    isUnlocked: (s) => s.watched.MOVIE.count >= 50,
    unlockHint: 'Watch 50 movies',
  },
  {
    id: 'cineaste',
    name: 'Cinéaste',
    description: 'Watched 100 movies.',
    icon: '🎬',
    shape: 'shield',
    color: '#dc2626',
    color2: '#9f1239',
    category: 'movies',
    isUnlocked: (s) => s.watched.MOVIE.count >= 100,
    unlockHint: 'Watch 100 movies',
  },

  // ── TV Shows ──────────────────────────────────────────────────────────
  {
    id: 'pilot',
    name: 'Pilot Episode',
    description: 'Watched your first TV show.',
    icon: '📺',
    shape: 'circle',
    color: '#0ea5e9',
    color2: '#38bdf8',
    category: 'tv',
    isUnlocked: (s) => s.watched.TV_SHOW.count >= 1,
    unlockHint: 'Watch your first TV show',
  },
  {
    id: 'binge_watcher',
    name: 'Binge Watcher',
    description: 'Watched 10 TV shows.',
    icon: '🛋️',
    shape: 'circle',
    color: '#0891b2',
    color2: '#0e7490',
    category: 'tv',
    isUnlocked: (s) => s.watched.TV_SHOW.count >= 10,
    unlockHint: 'Watch 10 TV shows',
  },
  {
    id: 'series_stalker',
    name: 'Series Veteran',
    description: 'Watched 50 TV shows.',
    icon: '📡',
    shape: 'shield',
    color: '#0369a1',
    color2: '#1d4ed8',
    category: 'tv',
    isUnlocked: (s) => s.watched.TV_SHOW.count >= 50,
    unlockHint: 'Watch 50 TV shows',
  },

  // ── Anime ─────────────────────────────────────────────────────────────
  {
    id: 'otaku_initiate',
    name: 'Otaku Initiate',
    description: 'Watched your first anime.',
    icon: '🌸',
    shape: 'circle',
    color: '#ec4899',
    color2: '#f9a8d4',
    category: 'anime',
    isUnlocked: (s) => s.watched.ANIME.count >= 1,
    unlockHint: 'Watch your first anime',
  },
  {
    id: 'otaku',
    name: 'Otaku',
    description: 'Watched 5 anime titles.',
    icon: '🐉',
    shape: 'circle',
    color: '#a855f7',
    color2: '#ec4899',
    category: 'anime',
    isUnlocked: (s) => s.watched.ANIME.count >= 5,
    unlockHint: 'Watch 5 anime',
  },
  {
    id: 'weeb',
    name: 'Anime Weeb',
    description: 'Watched 20 anime titles.',
    icon: '🌊',
    shape: 'hexagon',
    color: '#7c3aed',
    color2: '#a855f7',
    category: 'anime',
    isUnlocked: (s) => s.watched.ANIME.count >= 20,
    unlockHint: 'Watch 20 anime',
  },
  {
    id: 'anime_connoisseur',
    name: 'Anime Connoisseur',
    description: 'Watched 50 anime titles.',
    icon: '👾',
    shape: 'shield',
    color: '#4f46e5',
    color2: '#7c3aed',
    category: 'anime',
    isUnlocked: (s) => s.watched.ANIME.count >= 50,
    unlockHint: 'Watch 50 anime',
  },
  {
    id: 'anime_legend',
    name: 'Anime Legend',
    description: 'Watched 100 anime titles.',
    icon: '🧙',
    shape: 'star',
    color: '#312e81',
    color2: '#4338ca',
    category: 'anime',
    isUnlocked: (s) => s.watched.ANIME.count >= 100,
    unlockHint: 'Watch 100 anime',
  },

  // ── Reviews ───────────────────────────────────────────────────────────
  {
    id: 'first_opinion',
    name: 'First Opinion',
    description: 'Wrote your first review.',
    icon: '✍️',
    shape: 'circle',
    color: '#059669',
    color2: '#10b981',
    category: 'reviews',
    isUnlocked: (s) => s.watched.reviewCount >= 1,
    unlockHint: 'Write your first review (rating + notes)',
  },
  {
    id: 'critic',
    name: 'The Critic',
    description: 'Wrote 10 reviews.',
    icon: '🖊️',
    shape: 'hexagon',
    color: '#047857',
    color2: '#059669',
    category: 'reviews',
    isUnlocked: (s) => s.watched.reviewCount >= 10,
    unlockHint: 'Write 10 reviews',
  },
  {
    id: 'roger_ebert',
    name: 'Roger Ebert',
    description: 'Wrote 50 reviews.',
    icon: '📰',
    shape: 'star',
    color: '#065f46',
    color2: '#047857',
    category: 'reviews',
    isUnlocked: (s) => s.watched.reviewCount >= 50,
    unlockHint: 'Write 50 reviews',
  },

  // ── Watch Time ────────────────────────────────────────────────────────
  {
    id: 'weekend_warrior',
    name: 'Weekend Warrior',
    description: 'Accumulated 24 hours of watch time.',
    icon: '⏱️',
    shape: 'circle',
    color: '#0f766e',
    color2: '#0891b2',
    category: 'watchtime',
    isUnlocked: (s) => s.watched.totalMins >= 1440,
    unlockHint: 'Accumulate 24 hours of watch time',
  },
  {
    id: 'screen_addict',
    name: 'Screen Addict',
    description: 'Accumulated 100 hours of watch time.',
    icon: '📺',
    shape: 'hexagon',
    color: '#0e7490',
    color2: '#155e75',
    category: 'watchtime',
    isUnlocked: (s) => s.watched.totalMins >= 6000,
    unlockHint: 'Accumulate 100 hours of watch time',
  },
  {
    id: 'couch_legend',
    name: 'Couch Legend',
    description: 'Accumulated 500 hours of watch time.',
    icon: '🛋️',
    shape: 'star',
    color: '#164e63',
    color2: '#0c4a6e',
    category: 'watchtime',
    isUnlocked: (s) => s.watched.totalMins >= 30000,
    unlockHint: 'Accumulate 500 hours of watch time',
  },
];

export type AwardCategory = Award['category'];

export const CATEGORY_LABELS: Record<AwardCategory, string> = {
  milestone: 'Milestones',
  movies: 'Movies',
  tv: 'TV Shows',
  anime: 'Anime',
  reviews: 'Reviews',
  watchtime: 'Watch Time',
};

export function getUnlockedAwards(stats: ProfileStats): string[] {
  return AWARDS.filter((a) => a.isUnlocked(stats)).map((a) => a.id);
}
